### ISSUE TITLE
VINOD FINISH OUR SPOTIFY

### ISSUE THREAD

**Issue by kchq** [CSE512-15S/fp-kchq-vinodr-sonjak3-rileymp2#11]

**Comment by vrathnam7** [comment]
THANKS KEVIN!!!! Its looking good so far. Have got it to show up in the single artist view. Will work on head to head view next.

Right now it is simply showing tracks from a set of random songs. Still need to get the songs from actual artists or collabs by mapping out the information from the links. May map that out now so it is ready to go once the links show up.

**Comment by vrathnam7** [comment]
This is done now. It is missing a lot of the tracks. If we all have time to just kind of look through the collabs_pruned_with_spotify when we have free time, we can add in any that are missing.
