### ISSUE TITLE
Drake is from Canada.... that's awkward?

### ISSUE THREAD

**Issue by kchq** [CSE512-15S/fp-kchq-vinodr-sonjak3-rileymp2#3]
Thoughts?

**Comment by rileyporter** [comment]
Well.... if we really want to only show hip hop collabs in the US we should probably delete him from our dataset :(

**Comment by sonjakhan** [comment]
:dizzy_face:

**Comment by vrathnam7** [comment]
Ya I think that would probably be the right thing to do, or we would have to include Canada. Does it make sense to include him in any of the existing regions? That might not be a good idea since it provides inaccurate information to the user.

**Comment by sonjakhan** [comment]
Ok, so toronto doesn't fit in the zoomed in region for NE (or MW, although it's pretty close to fitting).
