### ISSUE TITLE
Tooltips on the links in the outer view giving some statistics about the artists/total collabs?

### ISSUE THREAD

**Issue by kchq** [CSE512-15S/fp-kchq-vinodr-sonjak3-rileymp2#4]

**Comment by vrathnam7** [comment]
I think this should not go into specifics about the artists. Since that information is available when they zoom into the region view. I think the total collabs will be useful though.

**Comment by SonjaKhan** [comment]
this took way longer than it needed to. :fu: tooltips

**Comment by sonjakhan** [comment]
this took way longer than it needed to. :fu: tooltips
